-- GERADO por supabase/especialidades-manifesto/gerar-importacao.mjs — NÃO editar à mão.
-- Manifesto: área TE, versão 1 (TESTE LOCAL — nunca vai para migration); 2 especialidade(s); sha256 d937d57504afa2aa769488b0974f9a8eebdec1b3c48b5131004f149bf089aed7
-- Fonte: [TESTE] fonte fictícia — https://exemplo.teste/fonte-ficticia — consultada em 2026-09-30 — conferido
do $especialidades$
declare v_existente text;
begin
  select fonte_hash into v_existente from public.curriculum_versions where identificador = 'especialidades-teste-local' and versao = '1';
  if found then
    if v_existente is distinct from 'd937d57504afa2aa769488b0974f9a8eebdec1b3c48b5131004f149bf089aed7' then
      raise exception 'Especialidades especialidades-teste-local: a versão 1 já existe com OUTRO conteúdo — publique uma versão nova do manifesto.';
    end if;
    raise notice 'Especialidades especialidades-teste-local: versão 1 já importada (mesmo conteúdo).';
    return;
  end if;
  insert into public.curriculum_versions (id, origem, identificador, versao, vigente_desde, status, fonte_url, fonte_descricao, fonte_hash, fonte_arquivo, importado_em, fonte_detalhes)
  values ('eb96bbdd-1a29-a914-165b-edd5482889a9', 'oficial', 'especialidades-teste-local', '1', '2026-09-30', 'publicado', 'https://exemplo.teste/fonte-ficticia',
    'Especialidades — [TESTE] Área de teste local. Importado do manifesto (supabase/especialidades-manifesto), versão 1.',
    'd937d57504afa2aa769488b0974f9a8eebdec1b3c48b5131004f149bf089aed7', 'supabase/especialidades-manifesto/teste', now(),
    '{"manifesto_versao":1,"area":"TE","fonte":{"nome":"[TESTE] fonte fictícia","url":"https://exemplo.teste/fonte-ficticia","consultada_em":"2026-09-30","status":"conferido"},"teste":true}'::jsonb);
  insert into public.specialties (id, curriculum_version_id, codigo, nome, categoria, nivel, ordem, fonte_url, fonte_consultada_em, fonte_revisao, status_fonte, manifesto_hash)
  values ('e8c2d462-d52c-e51d-e07b-6ff413a72015', 'eb96bbdd-1a29-a914-165b-edd5482889a9', 'TE-001', '[TESTE] Especialidade de Teste do Motor', '[TESTE] Área de teste local', '1', 10, 'https://exemplo.teste/fonte-ficticia', '2026-09-30', null, 'conferido', 'd937d57504afa2aa769488b0974f9a8eebdec1b3c48b5131004f149bf089aed7');
  insert into public.specialty_requirement_groups (id, specialty_id, chave, rotulo, minimo) values ('b2fc5ddf-520c-8140-4778-02ebaaa57e3f', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', 'tecnicas', 'Técnicas (faça 2 de 4)', 2);
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('7a7a7d2c-2ed8-cb32-4256-3e415607bd62', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '1', '[TESTE] Ler o texto fictício de apoio.', 'leitura', false, 10, '{"versao":1,"campos":[{"chave":"li","tipo":"confirmacao","rotulo":"Li o texto","obrigatorio":true}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.1');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('5398faa6-027a-62de-5a18-233eb9d3b370', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '2', '[TESTE] Responder por escrito a pergunta fictícia.', 'resposta', false, 20, '{"versao":1,"campos":[{"chave":"resposta","tipo":"texto_longo","rotulo":"Sua resposta","obrigatorio":true,"max":1000}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.2');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('46050d2e-81ba-c899-00f8-0598e72a5079', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '3', '[TESTE] Relatar a visita fictícia.', 'relatorio', false, 30, '{"versao":1,"campos":[{"chave":"data","tipo":"data","rotulo":"Data","obrigatorio":true,"nao_futura":true},{"chave":"local","tipo":"texto_curto","rotulo":"Local","obrigatorio":true,"max":150},{"chave":"descricao","tipo":"texto_longo","rotulo":"O que você fez","obrigatorio":true,"max":1500},{"chave":"fotos","tipo":"anexos","rotulo":"Fotos (opcional)","obrigatorio":false,"min":0,"max":3,"tipos":["imagem"]}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.3');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('f024bd13-8452-8723-6c6f-fd95eb69a136', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '4', '[TESTE] Enviar 1 foto do trabalho fictício.', 'foto', false, 40, '{"versao":1,"campos":[{"chave":"foto","tipo":"anexos","rotulo":"Foto do trabalho","obrigatorio":true,"min":1,"max":1,"tipos":["imagem"]}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.4');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('c5268b8d-646b-97a6-8721-3ffc17346f78', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '5', '[TESTE] Enviar 2 a 4 arquivos do projeto fictício.', 'arquivo', false, 50, '{"versao":1,"campos":[{"chave":"arquivos","tipo":"anexos","rotulo":"Arquivos do projeto","obrigatorio":true,"min":2,"max":4,"tipos":["arquivo","imagem"]}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.5');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('213fe822-4c8d-031d-7d54-c51f11db3f03', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '6', '[TESTE] Realizar a atividade prática fictícia.', 'atividade', false, 60, '{"versao":1,"campos":[{"chave":"fiz","tipo":"confirmacao","rotulo":"Fiz a atividade","obrigatorio":true},{"chave":"obs","tipo":"texto_curto","rotulo":"Observação (opcional)","obrigatorio":false,"max":200}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.6');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('d0323b13-29f3-ec53-4c22-9949c8ea53b5', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '7', '[TESTE] Demonstrar a habilidade fictícia ao instrutor.', 'validacao', false, 70, '{"versao":1,"campos":[{"chave":"demonstrei","tipo":"confirmacao","rotulo":"Demonstrei ao instrutor","obrigatorio":true}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.7');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('94ebbfa9-3924-7e5e-ad55-cc221199688d', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '8', '[TESTE] Praticar por no mínimo 4 dias (meta).', 'atividade', false, 80, '{"versao":1,"campos":[{"chave":"dias","tipo":"numero","rotulo":"Dias praticados","obrigatorio":true,"min":4,"unidade":"dias","inteiro":true},{"chave":"fiz","tipo":"confirmacao","rotulo":"Confirmo os dias","obrigatorio":true}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.8');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('45ad582d-4f00-bb22-c4af-d5e176d884e4', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '9', '[TESTE] Explicar o que aprendeu (só depois do requisito 2).', 'resposta', false, 90, '{"versao":1,"campos":[{"chave":"resposta","tipo":"texto_longo","rotulo":"Sua explicação","obrigatorio":true,"max":1000}]}'::jsonb, null, array['2']::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.9');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('d316eb49-c8dc-fd71-cddd-e00b720e8e8a', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '10', '[TESTE] Técnica A (faça 2 das 4 técnicas).', 'atividade', false, 100, '{"versao":1,"campos":[{"chave":"fiz","tipo":"confirmacao","rotulo":"Fiz a técnica A","obrigatorio":true}]}'::jsonb, 'tecnicas', '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.10');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('e6cf3633-dc4a-f765-d902-c8b3fd333979', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '11', '[TESTE] Técnica B (faça 2 das 4 técnicas).', 'atividade', false, 110, '{"versao":1,"campos":[{"chave":"fiz","tipo":"confirmacao","rotulo":"Fiz a técnica B","obrigatorio":true}]}'::jsonb, 'tecnicas', '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.11');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('cbba6d9f-04db-2666-3481-2a97117d861c', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '12', '[TESTE] Técnica C (faça 2 das 4 técnicas).', 'atividade', false, 120, '{"versao":1,"campos":[{"chave":"fiz","tipo":"confirmacao","rotulo":"Fiz a técnica C","obrigatorio":true}]}'::jsonb, 'tecnicas', '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.12');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('d2b7a863-2168-3d14-83d0-5833efbdc94c', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '13', '[TESTE] Técnica D (faça 2 das 4 técnicas).', 'atividade', false, 130, '{"versao":1,"campos":[{"chave":"fiz","tipo":"confirmacao","rotulo":"Fiz a técnica D","obrigatorio":true}]}'::jsonb, 'tecnicas', '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.13');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('5696227e-0992-547b-30df-50401fcd03c4', 'e8c2d462-d52c-e51d-e07b-6ff413a72015', '14', '[TESTE] Entregar a resposta final em até 30 dias (prazo).', 'resposta', false, 140, '{"versao":1,"campos":[{"chave":"resposta","tipo":"texto_longo","rotulo":"Sua resposta final","obrigatorio":true,"max":1000}]}'::jsonb, null, '{}'::text[], 30, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-001.14');
  insert into public.specialties (id, curriculum_version_id, codigo, nome, categoria, nivel, ordem, fonte_url, fonte_consultada_em, fonte_revisao, status_fonte, manifesto_hash)
  values ('f9d8d39f-76d4-0e3f-bf6f-678b1c06af82', 'eb96bbdd-1a29-a914-165b-edd5482889a9', 'TE-002', '[TESTE] Especialidade Avançada de Teste (depende da TE-001)', '[TESTE] Área de teste local', '2', 20, 'https://exemplo.teste/fonte-ficticia', '2026-09-30', null, 'conferido', 'd937d57504afa2aa769488b0974f9a8eebdec1b3c48b5131004f149bf089aed7');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('b55506a4-06ae-0276-ff47-22fbb6a6693a', 'f9d8d39f-76d4-0e3f-bf6f-678b1c06af82', '1', '[TESTE] Primeira resposta da avançada.', 'resposta', false, 10, '{"versao":1,"campos":[{"chave":"resposta","tipo":"texto_longo","rotulo":"Sua resposta","obrigatorio":true,"max":500}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-002.1');
  insert into public.specialty_requirements (id, specialty_id, codigo, descricao, tipo_evidencia, evidencia_obrigatoria, ordem, modelo, grupo, depende_de, prazo_dias, fonte_url, status_fonte, manifesto_id)
  values ('d233309f-0c5b-0e09-1889-647018d1f685', 'f9d8d39f-76d4-0e3f-bf6f-678b1c06af82', '2', '[TESTE] Segunda resposta da avançada.', 'resposta', false, 20, '{"versao":1,"campos":[{"chave":"resposta","tipo":"texto_longo","rotulo":"Sua resposta","obrigatorio":true,"max":500}]}'::jsonb, null, '{}'::text[], null, 'https://exemplo.teste/fonte-ficticia', 'conferido', 'TE-002.2');
  if not exists (select 1 from public.specialties where id = 'e8c2d462-d52c-e51d-e07b-6ff413a72015') then raise exception 'Especialidades especialidades-teste-local: TE-002 depende de TE-001, que ainda não foi importada — importe a área dela primeiro.'; end if;
  insert into public.curriculum_dependencies (alvo_tipo, alvo_id, depende_de_tipo, depende_de_id) values ('specialty', 'f9d8d39f-76d4-0e3f-bf6f-678b1c06af82', 'specialty', 'e8c2d462-d52c-e51d-e07b-6ff413a72015') on conflict do nothing;
end $especialidades$;
