-- JANELA FASE 8 — INVARIANTES (somente leitura). Cada linha: "OK ..." ou "FALHOU ...". Rode depois de CADA migration.
\set ON_ERROR_STOP on
begin read only;
-- 1) toda tabela do schema public tem RLS ligada
select case when count(*) = 0 then 'OK   rls: todas as tabelas public têm RLS' else 'FALHOU rls: sem RLS em ' || string_agg(relname, ', ') end
  from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind = 'r' and not c.relrowsecurity;
-- 2) nenhuma função SECURITY DEFINER sem search_path fixo
select case when count(*) = 0 then 'OK   definer: todas com search_path fixo' else 'FALHOU definer sem search_path: ' || string_agg(proname, ', ') end
  from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prosecdef and not exists (select 1 from unnest(coalesce(p.proconfig, '{}')) c where c like 'search_path=%');
-- 3) anon só executa as RPCs públicas intencionais
select case when count(*) = 0 then 'OK   anon: só as RPCs públicas intencionais' else 'FALHOU anon executa: ' || string_agg(proname, ', ') end
  from pg_proc p where p.pronamespace = 'public'::regnamespace and p.prokind = 'f' and has_function_privilege('anon', p.oid, 'execute') and proname !~ '^(_|pg_)'
   and proname not in ('convite_hierarquia_abrir', 'documento_verificar', 'entrada_abrir_publico', 'manutencao_estado', 'parceiros_publico', 'planos_disponiveis', 'vitrine_clube_publico', 'vitrine_clubes_publico');
-- 4) anon sem escrita direta em tabela
select case when count(*) = 0 then 'OK   grants: anon sem INSERT/UPDATE/DELETE' else 'FALHOU anon com escrita direta em ' || string_agg(distinct table_name, ', ') end
  from information_schema.role_table_grants where table_schema = 'public' and grantee = 'anon' and privilege_type in ('INSERT', 'UPDATE', 'DELETE');
-- 5) existência por etapa (só exige o que o ledger já diz estar aplicado)
with l as (select version from supabase_migrations.schema_migrations)
select case when ok then 'OK   ' || item else 'FALHOU ' || item end from (
  select '514 leitura_materiais/minha_jornada' as item, to_regclass('public.leitura_materiais') is not null and to_regprocedure('public.minha_jornada()') is not null as ok, '20260930000514' as v
  union all select '515 comunidade_posts.alcance + plataforma_acesso_log', exists (select 1 from information_schema.columns where table_name = 'comunidade_posts' and column_name = 'alcance') and to_regclass('public.plataforma_acesso_log') is not null, '20260930000515'
  union all select '516 audiolivros sem fonte desligados', not exists (select 1 from public.audiolivros where titulo in ('Expedição Galápagos', 'O Fim do Começo') and ativo), '20260930000516'
  union all select '517 rede_conquistas_publicaveis', to_regprocedure('public.rede_conquistas_publicaveis(text)') is not null, '20260930000517'
  union all select '518 classes_disponiveis com bloqueio/anterior (função existe)', to_regprocedure('public._classe_eh_anterior(uuid,uuid)') is not null, '20260930000518'
  union all select '519 classes_concluidas_anteriormente', to_regprocedure('public.classes_concluidas_anteriormente()') is not null, '20260930000519'
  union all select '520 relato_salvar', to_regprocedure('public.requisito_relato_salvar(uuid,text)') is not null and exists (select 1 from information_schema.columns where table_name = 'member_requirements' and column_name = 'relato'), '20260930000520'
  union all select '521 registro de conclusão anterior + log', to_regprocedure('public.classe_concluida_anteriormente_registrar(uuid,uuid,date,boolean,text,text)') is not null and to_regclass('public.class_prior_completion_log') is not null, '20260930000521'
  union all select '522 prévia de atualização + equivalências (vazia)', to_regprocedure('public.classe_atualizacao_previa(uuid)') is not null and to_regclass('public.class_requirement_equivalencias') is not null, '20260930000522'
  union all select '523 matrícula equivalente', to_regprocedure('public._classe_matricula_equivalente(uuid,uuid,uuid)') is not null, '20260930000523'
  union all select '524 fila unificada', to_regprocedure('public.fila_avaliacao_unificada(text,uuid)') is not null, '20260930000524'
  union all select '525 reconhecimentos de conclusão', to_regclass('public.class_completion_recognitions') is not null, '20260930000525'
  union all select '526 (mensagem) classe_iniciar existe', to_regprocedure('public.classe_iniciar(uuid)') is not null, '20260930000526'
  union all select '527 índice único de conquista ativa', exists (select 1 from pg_indexes where tablename = 'curriculum_achievements' and indexdef ilike '%classe_codigo%'), '20260930000527'
  union all select '528 webhook legado removido + 0 JWT literal em gatilho/função/view', not exists (select 1 from pg_trigger tg join pg_class c on c.oid = tg.tgrelid where c.relname = 'notificacoes' and tg.tgname = 'push-notificacoes') and (select count(*) from (select pg_get_triggerdef(tg.oid) txt from pg_trigger tg where not tg.tgisinternal union all select p.prosrc from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname not in ('pg_catalog', 'information_schema') union all select definition from pg_views where schemaname not in ('pg_catalog', 'information_schema')) a where txt ~ 'eyJ[A-Za-z0-9_-]{10,}.[A-Za-z0-9_-]{10,}.') = 0, '20260930000528'
  union all select '528 push novo (trg_notificacao_push) ativo', exists (select 1 from pg_trigger tg join pg_class c on c.oid = tg.tgrelid where c.relname = 'notificacoes' and tg.tgname = 'trg_notificacao_push' and tg.tgenabled = 'O'), '20260930000528'
  union all select '529 fila de saneamento + cron imagem-sanear existe (ligado em 01/10 depois da validação)', to_regclass('public.imagem_saneamento') is not null and to_regprocedure('public.imagem_saneamento_enfileirar(text,text)') is not null and exists (select 1 from cron.job where jobname = 'imagem-sanear'), '20260930000529'
  union all select '530 admin_comunidade_foto_assinar + colunas do log', to_regprocedure('public.admin_comunidade_foto_assinar(text,uuid)') is not null and exists (select 1 from information_schema.columns where table_name = 'plataforma_acesso_log' and column_name = 'bucket'), '20260930000530'
  union all select '531 catálogo e relatório do GC', to_regprocedure('public.admin_storage_gc_relatorio()') is not null or exists (select 1 from pg_proc where proname = 'admin_storage_gc_relatorio'), '20260930000531'
  union all select '532 fila de exclusão + 6 gatilhos + cron storage-excluir existe (ligado em 01/10 depois das provas) + lote 8 + carência 7', to_regclass('public.storage_exclusao_fila') is not null and (select count(*) from pg_trigger where tgname like 'zz_storage_exclusao_%' and not tgisinternal) = 6 and (public._storage_exclusao_politica() ->> 'lote_maximo')::int = 8 and (public._storage_exclusao_politica() ->> 'carencia_dias')::int = 7 and exists (select 1 from cron.job where jobname = 'storage-excluir'), '20260930000532'
  union all select '533 fila cobre rascunho/anexo: 9 gatilhos zz_storage_lacuna_* (nenhum apaga arquivo; só enfileira)', (select count(*) from pg_trigger where tgname like 'zz_storage_lacuna_%' and not tgisinternal) = 9 and to_regprocedure('public._storage_exclusao_gatilho_jsonb()') is not null, '20260930000533'
  union all select '534 push: registrada_em NOT NULL nas 2 tabelas + 6 funcoes so service_role (anon/authenticated sem EXECUTE; _push_mortas nem service_role) + poda NAO agendada', (select count(*) from information_schema.columns where table_schema='public' and table_name in ('push_subscriptions','push_tokens') and column_name='registrada_em' and is_nullable='NO') = 2 and (select count(*) from public.push_subscriptions where registrada_em is null) = 0 and to_regprocedure('public.push_remover_inscricao(bigint,text)') is not null and to_regprocedure('public.push_podar_inscricoes_mortas(boolean,integer,integer,uuid)') is not null and to_regprocedure('public.push_inscricoes_mortas(integer,integer,uuid)') is not null and to_regprocedure('public.push_resumo_erros(integer,uuid)') is not null and not exists (select 1 from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('push_remover_inscricao','push_podar_inscricoes_mortas','push_inscricoes_mortas','push_resumo_erros','_push_mortas','_push_carimbar_registro','push_reservar','push_concluir') and (has_function_privilege('anon',p.oid,'execute') or has_function_privilege('authenticated',p.oid,'execute'))) and not has_function_privilege('service_role','public._push_mortas(integer,integer,uuid)','execute') and not exists (select 1 from cron.job where command ilike '%push_podar%'), '20260930000534'
  union all select '535 stories para todos: constraint alcance (clube|comunidade) + rede_story_publicar(text,text,text) e rede_stories(text) sem overload antigo, SO authenticated executa (anon/public nao), search_path fixo, bucket comunidade privado', exists (select 1 from pg_constraint where conname = 'rede_stories_alcance_valido' and conrelid = 'public.rede_stories'::regclass) and not exists (select 1 from pg_constraint where conname = 'rede_stories_alcance_so_clube') and (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'rede_story_publicar') = 1 and (select count(*) from pg_proc where pronamespace = 'public'::regnamespace and proname = 'rede_stories') = 1 and to_regprocedure('public.rede_story_publicar(text,text,text)') is not null and to_regprocedure('public.rede_stories(text)') is not null and has_function_privilege('authenticated', 'public.rede_story_publicar(text,text,text)', 'execute') and has_function_privilege('authenticated', 'public.rede_stories(text)', 'execute') and not has_function_privilege('anon', 'public.rede_story_publicar(text,text,text)', 'execute') and not has_function_privilege('anon', 'public.rede_stories(text)', 'execute') and (select bool_and(coalesce(proconfig::text, '') like '%search_path%') from pg_proc where pronamespace = 'public'::regnamespace and proname in ('rede_story_publicar', 'rede_stories', '_rede_story_visivel', '_comunidade_pode_ver_foto')) and exists (select 1 from storage.buckets where id = 'comunidade' and not public), '20260930000535'
) x where v in (select version from l);
-- 6) ledger sem buracos fora da ordem da janela (informativo)
select 'INFO ledger_max = ' || max(version) from supabase_migrations.schema_migrations;
commit;
