// Fatos do "Guia do Aspirante" (Desbravadores, Ministério Jovem — União Nordeste Brasileira; 2ª edição, 2012),
// lidos página a página do PDF e reescritos com palavras próprias. Resumo da fonte: supabase/fontes/guia-do-aspirante-uneb-2012.md.
// Mesmo formato de historia.js: `q` pergunta, `t` afirmação com {}, `certa`, `errados` (3), `e` explicação.
export const MANUAL = [
  // ---- emblema, cores e bandeira ----
  { q: 'No emblema dos Desbravadores, o que o triângulo representa?', t: 'No emblema, o triângulo representa o crescimento {}.', certa: 'físico, mental e espiritual', errados: ['social, político e financeiro', 'moral, artístico e esportivo', 'individual, familiar e comunitário'], e: 'O triângulo lembra Lucas 2:52: crescimento físico, mental e espiritual.' },
  { q: 'No emblema, o que o escudo representa?', t: 'No emblema, o escudo representa {}.', certa: 'a fé em Jesus', errados: ['a proteção do clube', 'a coragem do desbravador', 'a unidade da igreja'], e: 'O escudo é a fé em Jesus.' },
  { q: 'No emblema, o que a espada representa?', t: 'No emblema, a espada representa {}.', certa: 'a Bíblia, a Palavra de Deus escrita', errados: ['a luta contra o mal', 'a disciplina do clube', 'a liderança do diretor'], e: 'A espada é a Bíblia, a Palavra de Deus escrita.' },
  { q: 'Nas cores do emblema, o azul simboliza o quê?', t: 'Nas cores do emblema, o azul simboliza {}.', certa: 'lealdade', errados: ['pureza', 'excelência', 'redenção'], e: 'Azul: lealdade. Amarelo: excelência dos ideais. Branco: pureza e santidade. Vermelho: o sangue de Cristo.' },
  { q: 'Nas cores do emblema, o amarelo simboliza o quê?', t: 'Nas cores do emblema, o amarelo simboliza {}.', certa: 'excelência dos ideais', errados: ['lealdade', 'pureza e santidade', 'o sangue de Cristo'], e: 'Amarelo: excelência dos ideais.' },
  { q: 'Nas cores do emblema, o branco simboliza o quê?', t: 'Nas cores do emblema, o branco simboliza {}.', certa: 'pureza e santidade', errados: ['lealdade', 'excelência dos ideais', 'o sangue de Cristo'], e: 'Branco: pureza e santidade.' },
  { q: 'Nas cores do emblema, o vermelho lembra o quê?', t: 'Nas cores do emblema, o vermelho lembra {}.', certa: 'o sangue de Cristo', errados: ['a coragem', 'a lealdade', 'a natureza'], e: 'Vermelho: o sangue de Cristo derramado na cruz, que nos dá redenção.' },
  { q: 'Quantas cores tem a bandeira do clube segundo o manual?', t: 'A bandeira do clube tem {} cores.', certa: '4', errados: ['2', '3', '5'], e: 'São quatro: duas partes azuis e duas brancas, mais as cores do triângulo.' },
  { q: 'Quais são as medidas da bandeira do clube (altura x largura)?', t: 'A bandeira do clube mede {}.', certa: '90 cm x 135 cm', errados: ['60 cm x 90 cm', '100 cm x 150 cm', '135 cm x 90 cm'], e: 'Mede 90 cm de altura por 135 cm de largura.' },
  { q: 'Qual é a medida do triângulo no centro da bandeira?', t: 'O triângulo no centro da bandeira mede {}.', certa: '30 cm de altura e 30 cm de largura', errados: ['10 cm x 10 cm', '45 cm x 45 cm', '60 cm x 30 cm'], e: 'O triângulo central mede 30 cm por 30 cm.' },
  { q: 'Onde fica escrito o nome do clube na bandeira?', t: 'O nome do clube fica escrito {}.', certa: 'na parte inferior direita, em letras brancas', errados: ['no topo, em letras azuis', 'dentro do triângulo, em letras amarelas', 'na parte inferior esquerda, em letras vermelhas'], e: 'Na parte inferior direita, em letras brancas.' },
  // ---- hino e saudação ----
  { q: 'Em que ano o hino dos Desbravadores foi oficializado, segundo o manual?', t: 'O hino dos Desbravadores foi oficializado em {}.', certa: '1952', errados: ['1949', '1950', '1961'], e: 'A ideia veio em 1949 e o hino foi oficializado em 1952.' },
  { q: 'Em que ano o Pr. Henry Bergh teve a ideia do hino enquanto dirigia?', t: 'A ideia do hino surgiu em maio de {}.', certa: '1949', errados: ['1922', '1946', '1952'], e: 'Em maio de 1949. A comissão de música dos Arautos do Rei aprovou o hino sem alterações.' },
  { q: 'Qual grupo musical aprovou o hino sem nenhuma alteração?', t: 'O hino foi aprovado, sem alteração, pelos {}.', certa: 'Arautos do Rei', errados: ['Vozes da Esperança', 'Meninos Cantores', 'Heraldos da Fé'], e: 'A comissão de música dos Arautos do Rei.' },
  { q: 'O que os quatro dedos levantados na saudação Maranata representam?', t: 'Na saudação Maranata, os quatro dedos lembram os quatro {}.', certa: '"A" de Amar, Anunciar, Apressar e Aguardar', errados: ['pontos cardeais', 'itens do voto', 'pilares do clube'], e: 'Amar, Anunciar, Apressar e Aguardar a vinda de Jesus.' },
  { q: 'Na saudação Maranata, o que o polegar curvado representa?', t: 'Na saudação Maranata, o polegar curvado representa {}.', certa: 'o desbravador ajoelhado, pronto a servir', errados: ['o diretor do clube', 'a união da unidade', 'a Bíblia aberta'], e: 'Representa o desbravador ajoelhado e pronto para amar, anunciar, apressar e aguardar a vinda de Jesus.' },
  // ---- lei e voto ----
  { q: 'Quantos itens tem a Lei do Desbravador?', t: 'A Lei do Desbravador tem {} itens.', certa: '8', errados: ['6', '10', '12'], e: 'São oito itens, do "observar a devoção matinal" ao "ir onde Deus mandar".' },
  { q: 'Qual é o primeiro item da Lei do Desbravador?', t: 'O primeiro item da Lei do Desbravador é {}.', certa: 'observar a devoção matinal', errados: ['cuidar do meu corpo', 'ser cortês e obediente', 'ir onde Deus mandar'], e: 'O primeiro item é observar a devoção matinal.' },
  { q: 'Qual é o último item da Lei do Desbravador?', t: 'O último item da Lei do Desbravador é {}.', certa: 'ir onde Deus mandar', errados: ['observar a devoção matinal', 'ter sempre um cântico no coração', 'manter a consciência limpa'], e: 'O oitavo item é ir onde Deus mandar.' },
  { q: 'Segundo o Voto, o desbravador promete ser puro, bondoso e o quê?', t: 'No Voto, o desbravador promete ser puro, bondoso e {}.', certa: 'leal', errados: ['forte', 'valente', 'alegre'], e: 'Puro, bondoso e leal; servo de Deus e amigo de todos.' },
  // ---- unidade e clube ----
  { q: 'Qual é o máximo de membros de uma unidade, segundo o manual?', t: 'Cada unidade tem, no máximo, {} membros.', certa: '8', errados: ['5', '10', '12'], e: 'Cada unidade tem no máximo 8 membros, liderados por um conselheiro adulto.' },
  { q: 'Quem lidera as unidades femininas?', t: 'As unidades femininas são lideradas por uma {}.', certa: 'conselheira', errados: ['capitã', 'instrutora', 'secretária'], e: 'As femininas têm conselheira; as masculinas, conselheiro.' },
  { q: 'Quem é o capitão da unidade?', t: 'O capitão da unidade é {}.', certa: 'um desbravador escolhido pela unidade para incentivar o cumprimento do programa', errados: ['o conselheiro adulto da unidade', 'o instrutor do clube', 'o diretor associado'], e: 'O capitão é um desbravador escolhido pela unidade; o conselheiro é o líder adulto.' },
  { q: 'Por quanto tempo costumam durar os cargos de capitão e secretário da unidade?', t: 'Os cargos de capitão e secretário da unidade duram de {}.', certa: '3 meses a 1 ano', errados: ['1 semana a 1 mês', '2 a 3 anos', 'a vida toda'], e: 'São cargos temporários, para que outros desbravadores também exerçam funções.' },
  { q: 'Quem cuida das unidades masculinas no clube?', t: 'Quem cuida das unidades masculinas é {}.', certa: 'o diretor associado', errados: ['a diretora associada', 'a secretária', 'o capelão'], e: 'O diretor associado cuida das masculinas e a diretora associada, das femininas.' },
  { q: 'Quem tem a tarefa de ensinar as classes e especialidades?', t: 'O ensino das classes e especialidades é tarefa dos {}.', certa: 'conselheiros e instrutores', errados: ['capitães', 'secretários', 'pastores distritais'], e: 'É tarefa dos conselheiros e instrutores.' },
  // ---- uniforme, classes e ordem unida ----
  { q: 'Quantos dias o novo desbravador tem para obter o uniforme oficial, segundo o manual?', t: 'O novo desbravador tem {} dias para obter o uniforme oficial.', certa: '90', errados: ['30', '60', '180'], e: 'Depois disso passa pela avaliação e pela cerimônia do lenço.' },
  { q: 'Quantos requisitos a lista do manual traz para a cerimônia do lenço?', t: 'A lista para a cerimônia do lenço tem {} requisitos.', certa: '10', errados: ['5', '8', '12'], e: 'São dez, de "estar matriculado no clube" a "estar em dias com a cota".' },
  { q: 'Segundo o manual, a partir de que idade se usa camisa branca no uniforme oficial?', t: 'No uniforme oficial, quem tem mais de {} anos usa camisa branca.', certa: '15', errados: ['12', '14', '18'], e: 'Quem tem acima de 15 anos usa camisa branca.' },
  { q: 'Em que idade começa a classe de Líder, segundo o manual?', t: 'A classe de Líder começa aos {} anos.', certa: '16', errados: ['15', '18', '20'], e: 'Líder 16 anos, Líder Máster 18 e Líder Máster Avançado 20.' },
  { q: 'Dos 10 até qual idade vai o programa de classes do clube, segundo o manual?', t: 'O programa de classes vai dos 10 aos {} anos (Líder Máster Avançado).', certa: '20', errados: ['15', '16', '18'], e: 'Começa com a classe de Amigo, aos 10, e vai até Líder Máster Avançado, aos 20.' },
  { q: 'Na ordem unida, como se chama o primeiro desbravador de uma coluna?', t: 'Na ordem unida, o primeiro desbravador de uma coluna é a {}.', certa: 'testa', errados: ['cauda', 'base', 'cobertura'], e: 'Testa é o primeiro; cauda é o último.' },
  { q: 'Na ordem unida, como se chama o último desbravador de uma coluna?', t: 'Na ordem unida, o último desbravador de uma coluna é a {}.', certa: 'cauda', errados: ['testa', 'base', 'fila'], e: 'Cauda é o último; testa é o primeiro.' },
  { q: 'Na ordem unida, o que é uma fila?', t: 'Na ordem unida, fila é quando os desbravadores estão {}.', certa: 'lado a lado', errados: ['um atrás do outro', 'em círculo', 'em duas colunas'], e: 'Fila é um ao lado do outro; coluna é um atrás do outro.' },
  { q: 'Na ordem unida, o que é uma coluna?', t: 'Na ordem unida, coluna é quando os desbravadores estão {}.', certa: 'um atrás do outro', errados: ['lado a lado', 'em círculo', 'de costas'], e: 'Coluna é um atrás do outro; fila é lado a lado.' },
  { q: 'Qual dessas é uma "voz" da ordem unida?', t: 'A voz de {} é uma das três vozes da ordem unida.', certa: 'comando', errados: ['sentido', 'marcha', 'alinhamento'], e: 'As três vozes são advertência, comando e execução.' },
  // ---- história do manual ----
  { q: 'Segundo o manual, em que ano Arthur Spalding e Harriet Holt formaram a primeira ideia do clube?', t: 'Arthur Spalding e Harriet Holt formaram a primeira ideia do clube em {}.', certa: '1922', errados: ['1920', '1946', '1950'], e: 'Foi em 1922.' },
  { q: 'Em que cidade da Califórnia, na década de 30, um casal organizou em casa o primeiro clube com o nome de desbravadores?', t: 'Na década de 30, o clube organizado em casa por um casal ficava em {}, Califórnia.', certa: 'Santa Ana', errados: ['Riverside', 'Idyllwild', 'Dinuba'], e: 'Foi em Santa Ana, tendo John Mckim como diretor.' },
  { q: 'Em 1946, em qual igreja o clube foi organizado com a ajuda de John H. Hancock?', t: 'Em 1946 o clube foi organizado na igreja de {}.', certa: 'Riverside', errados: ['Santa Ana', 'Miraflores', 'Temuco'], e: 'Na igreja de Riverside, na Califórnia.' },
  { q: 'Quem desenhou o emblema (o triângulo) dos Desbravadores?', t: 'O emblema (o triângulo) foi desenhado por John {}.', certa: 'Hancock', errados: ['Youngberg', 'Skinner', 'Fattic'], e: 'O Pr. John Hancock desenhou o triângulo.' },
  { q: 'Quem foi o primeiro líder mundial dos Desbravadores, de 1950 a 1963?', t: 'O primeiro líder mundial dos Desbravadores (1950 a 1963) foi L. {}.', certa: 'Skinner', errados: ['Hancock', 'Spalding', 'Lester'], e: 'L. Skinner, de 1950 a 1963; depois John Hancock, de 1963 a 1970.' },
]
