// Vocabulário do clube para os jogos de palavras (Forca, Anagrama, Caça-palavras, Morse, Termo).
// Só A–Z maiúsculo, sem acento nem cedilha (LENÇO = LENCO) e sem espaço. Fonte: classes e requisitos do manifesto, o Guia do
// Aspirante, as páginas Símbolos e Origem histórica e o vocabulário de campo que os jogos já usavam.
const GRUPOS = {
  campo: `FOGO TENDA MAPA MATA TROPA NORTE SUL LESTE OESTE CORDA BUSSOLA LANTERNA MOCHILA BARRACA CANIVETE FOGUEIRA ACAMPAMENTO
    CAMINHADA CANTINA NATUREZA ESTRELAS RIACHO TRILHA SINAIS PISTA MACHADINHA FACA NOS AMARRA PIONEIRIA ABRIGO LENHA BRASA
    MATERIAL MAPAS ROTEIRO ORIENTACAO SEMAFORA MORSE BANDEIRINHA CAMPING ESCALADA VIGILIA PANELA CANTIL BOTAS`,
  clube: `DESBRAVADOR DESBRAVADORA CLUBE UNIDADE CLASSE ESPECIALIDADE INVESTIDURA CONSELHEIRO CONSELHEIRA CAPITAO CAPITA SECRETARIO TESOUREIRO DIRETOR
    DIRETORA DIRETORIA INSTRUTOR CAPELAO LIDER MASTER AVANCADA REGULAR ASPIRANTE MEMBRO AGENDA REUNIAO CERIMONIA ADMISSAO
    MATRICULA COTA UNIFORME LENCO INSIGNIA SISTEMA ESTRUTURA ASSOCIACAO MISSAO REGIAO DISTRITO IGREJA PASTOR`,
  classes: `AMIGO COMPANHEIRO PESQUISADOR PIONEIRO EXCURSIONISTA GUIA`,
  simbolos: `VOTO LEI ALVO LEMA OBJETIVO HINO BANDEIRA EMBLEMA TRIANGULO ESCUDO ESPADA MARANATA FIDELIDADE BIBLIA LEALDADE PUREZA
    EXCELENCIA SANTIDADE REDENCAO TRINDADE SIMBOLOS IDEAIS CORES AZUL AMARELO BRANCO VERMELHO SALVACAO SERVICO SACRIFICIO`,
  lei: `DEVOCAO MATINAL CORPO CONSCIENCIA CORTES OBEDIENTE REVERENCIA CANTICO CORACAO SERVO AMIGOS BONDOSO PURO LEAL
    TEMPERANTE HONESTO FIEL ALEGRE REVERENTE`,
  ordemUnida: `COLUNA FILA COBERTURA ALINHAMENTO BASE TESTA CAUDA SENTIDO DESCANSAR FIRME COMANDO EXECUCAO ADVERTENCIA FORMACAO
    MARCHA ORDEM VOLVER VOZES MOVIMENTOS`,
  historia: `CAMPORI CALIFORNIA MICHIGAN PERU CHILE BRASIL URUGUAI BOLIVIA EQUADOR LIMA TEMUCO GUAYAQUIL LAJEADO RIVERSIDE HANCOCK
    SKINNER SPALDING FEYRABEND MIRAFLORES ARAUTOS PATHFINDER CONQUISTADORES DESBRAVADORES FUNDADORES ORIGEM HISTORIA ANIVERSARIO
    SANTA CATARINA PAULO CANADA ARGENTINA`,
  biblia: `GENESIS EXODO LEVITICO NUMEROS DEUTERONOMIO JOSUE JUIZES RUTE SAMUEL REIS CRONICAS ESDRAS NEEMIAS ESTER SALMOS PROVERBIOS
    ECLESIASTES ISAIAS JEREMIAS DANIEL JONAS MATEUS MARCOS LUCAS JOAO ATOS ROMANOS CORINTIOS APOCALIPSE ESPIRITO APOSTOLOS
    MANDAMENTOS PRAGAS TRIBOS ISRAEL EGITO CRIACAO SANTUARIO SERMAO MONTANHA PARABOLA MILAGRE JESUS DEUS CRISTO GRACA ANJOS
    SABADO PROFETA DAVI MOISES NOE ABRAAO JOSE SALOMAO ELIAS PAULO PEDRO TIAGO FRUTO FE ESPERANCA AMOR`,
  especialidades: `ARTESANATO PINTURA COSTURA CULINARIA HORTA CARPINTARIA ELETRICIDADE COMPUTACAO ALVENARIA FOTOGRAFIA COMUNICACAO
    CURATIVO BANDAGEM ATADURA TORNIQUETE SOCORROS PRIMEIROS NATACAO CICLISMO CORRIDA ESPORTES AVENTURA RECREACAO AGRICULTURA
    PECUARIA JARDIM POMAR APICULTURA ARTES HABILIDADES CIENCIA MISSIONARIA PROFISSIONAL DOMESTICA TECELAGEM CERAMICA DESENHO
    MUSICA VIOLAO FLAUTA CORAL TEATRO PRIMEIRO SOCORRO RESGATE SEGURANCA PREVENCAO`,
  natureza: `AGUIA CORUJA TUCANO ARARA ONCA LOBO URSO ALCE COBRA SAPO ABELHA FORMIGA BORBOLETA PINHEIRO CARVALHO ARVORE FOLHA RAIZ
    FLOR SEMENTE ESTRELA LUA SOL PLANETA COMETA CONSTELACAO CRUZEIRO FLORESTA CACHOEIRA MONTANHAS CAMPO BOSQUE CERRADO PANTANAL
    AMAZONIA PASSARO MAMIFERO REPTIL ANFIBIO INSETO CLIMA CHUVA VENTO NUVEM TROVAO ARCOIRIS COLINA VALE RIO LAGO MAR ILHA DESERTO`,
  nos: `ESCOTA LAIS PESCADOR DIRETO QUADRADA DIAGONAL REDONDA CHICOTE SEIO LACO VOLTA NO AMARRAS AMARRACAO TRONCO TORRE PORTAL`,
  pessoas: `ABEL CAIM ISAQUE JACO ESTEVAO TIMOTEO FILIPE ANDRE TOME JUDAS LAZARO MARIA MARTA RAQUEL SARA GIDEAO SANSAO SAMUEL
    JOAQUIM LIDIA DEBORA ESDRAS ABIGAIL JONATAS GOLIAS`,
  vida: `TEMPERANCA ALIMENTACAO EXERCICIO AGUA DESCANSO CONFIANCA SAUDE HIGIENE REMEDIOS NATURAIS HONRA SERVO UNIAO AMIZADE
    RESPEITO CORAGEM`,
}

const valida = (p) => /^[A-Z]{2,14}$/.test(p)
export const VOCABULARIO = [...new Set(Object.values(GRUPOS).flatMap((g) => g.split(/\s+/).filter(Boolean)))].filter(valida)

// Palavras com comprimento entre min e max (inclusive). Extras entram na lista (sem repetir).
export function palavras(min, max, extras = []) {
  return [...new Set([...extras, ...VOCABULARIO])].filter((p) => p.length >= min && p.length <= max)
}
